Use the `cloud.r-project.org` mirror
asdf-community/asdf-r pull request #8
Opened 2022-02-23 04:17 UTC by nokome

I recently had problems with connecting to the currently used CRAN mirror. This fixed the issue. The `cloud.r-project.org` mirror has "Automatic redirection to servers worldwide". As such it is likely to be more reliable, and performant, than any one CRAN mirror.

2022-02-23 16:48 UTC, taiar requested changes
Hi @nokome, thanks for the PR. I would accept it, it would be better to have the R Project's CRAN Mirror, for sure.

However, if you take a look on these 2 URLs:
- https://mirrors.nics.utk.edu/cran/src/base/R-4
- https://cloud.r-project.org/src/base/R-4

You will realize that those 2 repos are running different webservers, showing a different markup for those pages, which is breaking the `list-all` script who parses those page markups. When I ran your branch's `./bin/list-all`, I have an empty output, instead of showing the versions.

Would you also provide the fix for the `list-all` script?

2022-02-27 19:24 UTC, nokome commented
Hi @taiar. Oh yes, sorry I didn't test that `list-all` was still working. I'll fix it.

2022-02-27 22:16 UTC, nokome commented
I've fixed that now. Thanks for considering this PR!

2022-03-03 01:29 UTC, taiar commented
@nokome, please, allow me to make a small change to your code, more details on my commit https://github.com/asdf-community/asdf-r/pull/8/commits/4a5804abe746b478801a5a4416bb3d8daf6807fb

2022-03-03 01:30 UTC, taiar approved these changes

2022-03-03 01:30 UTC, merged

2022-03-03 10:58 UTC, taiar commented
Thank you @nokome!